import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfGenerator {
  static Future<Uint8List> generateRideReport({
    required int rideId,
    required List<dynamic> samples,
    required double avgAccel,
    required double avgDecel,
    required double avgSpeed,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageTheme: const pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: pw.EdgeInsets.all(32), // ✅ FIXED for pdf 3.11+
        ),
        build: (context) => [
          // 🔴 HEADER SECTION
          pw.Center(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Text(
                  "KINETIQ RIDE REPORT",
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.red,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  "Ride ID: #$rideId",
                  style: pw.TextStyle(
                    fontSize: 14,
                    color: PdfColors.grey700,
                  ),
                ),
                pw.Divider(thickness: 1, color: PdfColors.red),
                pw.SizedBox(height: 18),
              ],
            ),
          ),

          // 📊 SUMMARY SECTION
          pw.Text(
            "📊 Ride Summary",
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.red,
              fontSize: 18,
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Table.fromTextArray(
            headers: ['Metric', 'Value'],
            data: [
              ['Average Acceleration', '${avgAccel.toStringAsFixed(2)} m/s²'],
              ['Average Deceleration', '-${avgDecel.toStringAsFixed(2)} m/s²'],
              ['Average Speed', '${avgSpeed.toStringAsFixed(2)} km/h'],
            ],
            headerDecoration: const pw.BoxDecoration(color: PdfColors.red900),
            headerStyle: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
            ),
            cellStyle: pw.TextStyle(color: PdfColors.black),
            cellAlignment: pw.Alignment.centerLeft,
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          ),
          pw.SizedBox(height: 25),

          // 🧠 DATA TABLE SECTION
          pw.Text(
            "🧠 Recorded Data Points (${samples.length})",
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.red,
              fontSize: 18,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Table.fromTextArray(
            headers: const [
              'Time',
              'Speed (km/h)',
              'Accel (m/s²)',
              'Decel (m/s²)',
              'Lat',
              'Lon'
            ],
            data: samples
                .take(30) // limit rows to keep layout clean
                .map((s) => [
                      s.timestamp.toString().split('T').last.split('.').first,
                      s.speedKmh.toStringAsFixed(1),
                      s.axLong.toStringAsFixed(2),
                      s.decel.toStringAsFixed(2),
                      s.latitude.toStringAsFixed(4),
                      s.longitude.toStringAsFixed(4),
                    ])
                .toList(),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.red900),
            headerStyle: pw.TextStyle(
              color: PdfColors.white,
              fontWeight: pw.FontWeight.bold,
              fontSize: 11,
            ),
            cellStyle: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.black,
            ),
            cellAlignment: pw.Alignment.centerLeft,
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          ),
          pw.SizedBox(height: 35),

          // 🔚 FOOTER SECTION
          pw.Center(
            child: pw.Text(
              "Generated by KINETIQ – Rider Telemetry System",
              style: pw.TextStyle(
                color: PdfColors.grey600,
                fontSize: 10,
              ),
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }
}
